##

In [563]:
import pandas as pd
import numpy as np

# 
path = r"C:\Users\Youcode\Desktop\Brife2\projet_scrapting\projet_appartements.csv"
df = pd.read_csv(path)
data_catalog = {
    'Titre': 'Nom de l\'annonce (string)',
    'Localisation': 'Lieu de l\'annonce (string)',
    'Prix': 'Prix en dirhams (float)',
    'Nombre_chambre': 'Nombre de chambres (int)',
    'Nombre_douches': 'Nombre de salles de bain (int)',
    'Surface_habitable': 'Surface en m² (float)',
    'Type': 'Type de l\'annonce (catégoriel)',
    'Secteur': 'Secteur (string)',
    'Salons': 'Nombre de salons (int)',
    'Étage': 'Étage de l\'appartement (int)',
    'Âge_du_bien': 'Âge de la propriété (catégoriel)',
    'link': 'Lien vers l\'annonce (URL)'
}
df

,Titre,Localisation,Prix,Nombre_chambre,Nombre_douches,Surface_habitable,Type,Secteur,Salons,Étage,Âge_du_bien,link
0,APPARTEMENT À LOUER SUR CASABLANCA FINANCE CITY,Casablanca,7 600 DH,2,1.0,90.0,"Appartements, à louer",Casablanca Finance City,1.0,1,NaN,https://www.avito.ma/fr/casablanca_finance_cit...
1,Appartement à louer neuf,Temara,5 500 DH,2,2.0,94.0,"Appartements, à louer",Wifak,2.0,2,NaN,https://www.avito.ma/fr/wifak/appartements/App...
2,très belle appartement à louer,Agadir,300 DH /Nuit,3,1.0,NaN,"Locations de vacances, à louer",Hay Mohammadi,NaN,NaN,NaN,https://www.avito.ma/fr/hay_mohammadi/location...
3,appart meublé familiale sans intermédiaire Wi-Fi,Tanger,200 DH /Nuit,5+,3.0,NaN,"Locations de vacances, à louer",Marjane,NaN,NaN,NaN,https://www.avito.ma/fr/marjane/locations_de_v...
4,Appartement à vendre 121 m² à Casablanca,Casablanca,2 250 000 DH,3,3.0,121.0,"Appartements, à vendre",Maârif Extension,1.0,3,Neuf,https://www.avito.ma/fr/ma%C3%A2rif_extension/...
...,...,...,...,...,...,...,...,...,...,...,...,...
646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://immoneuf.avito.ma/fr/unite/jTW?utm_sou...
647,Appartement,Taza,370 000 DH,2,1.0,88.0,"Appartements, à vendre",Toute la ville,2.0,4,6-10 ans,https://www.avito.ma/fr/taza/appartements/Appa...
648,Studio-Appartement-Haut-Standing-Gueliz,Marrakech,19 000 DH,2,2.0,51.0,"Appartements, à vendre",Guéliz,1.0,5,Neuf,https://www.avito.ma/fr/gu%C3%A9liz/appartemen...
649,Appartement à vendre 60 m² prés de Acima Meknès,Meknès,249 999 DH,2,1.0,60.0,"Appartements, à vendre",Autre secteur,1.0,1,Neuf,https://www.avito.ma/fr/autre_secteur/appartem...
650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://immoneuf.avito.ma/fr/unite/jI8?utm_sou...

In [564]:
#
df.head()

,Titre,Localisation,Prix,Nombre_chambre,Nombre_douches,Surface_habitable,Type,Secteur,Salons,Étage,Âge_du_bien,link
0,APPARTEMENT À LOUER SUR CASABLANCA FINANCE CITY,Casablanca,7 600 DH,2,1.0,90.0,"Appartements, à louer",Casablanca Finance City,1.0,1,NaN,https://www.avito.ma/fr/casablanca_finance_cit...
1,Appartement à louer neuf,Temara,5 500 DH,2,2.0,94.0,"Appartements, à louer",Wifak,2.0,2,NaN,https://www.avito.ma/fr/wifak/appartements/App...
2,très belle appartement à louer,Agadir,300 DH /Nuit,3,1.0,NaN,"Locations de vacances, à louer",Hay Mohammadi,NaN,NaN,NaN,https://www.avito.ma/fr/hay_mohammadi/location...
3,appart meublé familiale sans intermédiaire Wi-Fi,Tanger,200 DH /Nuit,5+,3.0,NaN,"Locations de vacances, à louer",Marjane,NaN,NaN,NaN,https://www.avito.ma/fr/marjane/locations_de_v...
4,Appartement à vendre 121 m² à Casablanca,Casablanca,2 250 000 DH,3,3.0,121.0,"Appartements, à vendre",Maârif Extension,1.0,3,Neuf,https://www.avito.ma/fr/ma%C3%A2rif_extension/...

In [548]:
df.tail()

,Titre,Localisation,Prix,Nombre_chambre,Nombre_douches,Surface_habitable,Type,Secteur,Salons,Étage,Âge_du_bien,link
644,Appartement à vendre 66 m² à Dar Bouazza,Dar Bouazza,595000.0,2,2,66.0,NaN,Toute la ville,1,2,-1 ans,https://www.avito.ma/fr/dar_bouazza/appartemen...
645,Superbe appartement meublé pour vente,Tanger,1400000.0,2,1,78.0,NaN,Branes Kdima,1,5,-1 ans,https://www.avito.ma/fr/branes_kdima/apparteme...
647,Appartement,Taza,370000.0,2,1,88.0,NaN,Toute la ville,2,4,6-10 ans,https://www.avito.ma/fr/taza/appartements/Appa...
648,Studio-Appartement-Haut-Standing-Gueliz,Marrakech,19000.0,2,2,51.0,NaN,Guéliz,1,5,-1 ans,https://www.avito.ma/fr/gu%C3%A9liz/appartemen...
649,Appartement à vendre 60 m² prés de Acima Meknès,Meknès,249999.0,2,1,60.0,NaN,Autre secteur,1,1,-1 ans,https://www.avito.ma/fr/autre_secteur/appartem...

In [565]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651 entries, 0 to 650
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Titre              525 non-null    object
 1   Localisation       525 non-null    object
 2   Prix               525 non-null    object
 3   Nombre_chambre     523 non-null    object
 4   Nombre_douches     517 non-null    float64
 5   Surface_habitable  507 non-null    float64
 6   Type               525 non-null    object
 7   Secteur            525 non-null    object
 8   Salons             455 non-null    float64
 9   Étage              512 non-null    object
 10  Âge_du_bien        395 non-null    object
 11  link               651 non-null    object
dtypes: float64(3), object(9)
memory usage: 61.2+ KB

##  1 -netteyage Titre :

In [567]:
# verifier les lignes nan en colonne 'Titre'
ligne_nan = df[df['Titre'].isnull()]
print(ligne_nan)

    Titre Localisation Prix Nombre_chambre  Nombre_douches  Surface_habitable  \
39    NaN          NaN  NaN            NaN             NaN                NaN
44    NaN          NaN  NaN            NaN             NaN                NaN
49    NaN          NaN  NaN            NaN             NaN                NaN
54    NaN          NaN  NaN            NaN             NaN                NaN
59    NaN          NaN  NaN            NaN             NaN                NaN
..    ...          ...  ...            ...             ...                ...
631   NaN          NaN  NaN            NaN             NaN                NaN
636   NaN          NaN  NaN            NaN             NaN                NaN
641   NaN          NaN  NaN            NaN             NaN                NaN
646   NaN          NaN  NaN            NaN             NaN                NaN
650   NaN          NaN  NaN            NaN             NaN                NaN

    Type Secteur  Salons Étage Âge_du_bien  \
39   NaN     NaN     NaN   NaN         NaN
44   NaN     NaN     NaN   NaN         NaN
49   NaN     NaN     NaN   NaN         NaN
54   NaN     NaN     NaN   NaN         NaN
59   NaN     NaN     NaN   NaN         NaN
..   ...     ...     ...   ...         ...
631  NaN     NaN     NaN   NaN         NaN
636  NaN     NaN     NaN   NaN         NaN
641  NaN     NaN     NaN   NaN         NaN
646  NaN     NaN     NaN   NaN         NaN
650  NaN     NaN     NaN   NaN         NaN

                                                  link
39   https://immoneuf.avito.ma/fr/unite/jaY?utm_sou...
44   https://immoneuf.avito.ma/fr/unite/47h?utm_sou...
49   https://immoneuf.avito.ma/fr/unite/jZv?utm_sou...
54   https://immoneuf.avito.ma/fr/unite/jfl?utm_sou...
59   https://immoneuf.avito.ma/fr/unite/jcQ?utm_sou...
..                                                 ...
631  https://immoneuf.avito.ma/fr/unite/joQ?utm_sou...
636  https://immoneuf.avito.ma/fr/unite/4jE?utm_sou...
641  https://immoneuf.avito.ma/fr/unite/jXW?utm_sou...
646  https://immoneuf.avito.ma/fr/unite/jTW?utm_sou...
650  https://immoneuf.avito.ma/fr/unite/jI8?utm_sou...

[126 rows x 12 columns]

In [568]:
df.head()

,Titre,Localisation,Prix,Nombre_chambre,Nombre_douches,Surface_habitable,Type,Secteur,Salons,Étage,Âge_du_bien,link
0,APPARTEMENT À LOUER SUR CASABLANCA FINANCE CITY,Casablanca,7 600 DH,2,1.0,90.0,"Appartements, à louer",Casablanca Finance City,1.0,1,NaN,https://www.avito.ma/fr/casablanca_finance_cit...
1,Appartement à louer neuf,Temara,5 500 DH,2,2.0,94.0,"Appartements, à louer",Wifak,2.0,2,NaN,https://www.avito.ma/fr/wifak/appartements/App...
2,très belle appartement à louer,Agadir,300 DH /Nuit,3,1.0,NaN,"Locations de vacances, à louer",Hay Mohammadi,NaN,NaN,NaN,https://www.avito.ma/fr/hay_mohammadi/location...
3,appart meublé familiale sans intermédiaire Wi-Fi,Tanger,200 DH /Nuit,5+,3.0,NaN,"Locations de vacances, à louer",Marjane,NaN,NaN,NaN,https://www.avito.ma/fr/marjane/locations_de_v...
4,Appartement à vendre 121 m² à Casablanca,Casablanca,2 250 000 DH,3,3.0,121.0,"Appartements, à vendre",Maârif Extension,1.0,3,Neuf,https://www.avito.ma/fr/ma%C3%A2rif_extension/...

In [569]:
# si le titre est null , supprimer la ligne
df = df.dropna(subset=['Titre'])

In [570]:

# test est ce un ligne null en colonne 'Titre'
ligne_nan = df[df['Titre'].isnull()]
print(ligne_nan)

Empty DataFrame
Columns: [Titre, Localisation, Prix, Nombre_chambre, Nombre_douches, Surface_habitable, Type, Secteur, Salons, Étage, Âge_du_bien, link]
Index: []

In [571]:
# supprimer les espace dans la colonne Titre
df.loc[:, 'Titre'] = df['Titre'].str.strip()

## 2 - nettoyage la colonne 'Localisation'

In [572]:
# supprimer les espace dans la colonne Localistaion
df.loc[:, 'Localisation'] = df['Localisation'].str.strip()

## 3- nettoyer les colonne de 'Prix'

In [573]:
# remplacer les serie de nan if 'PRIX NON SPECIFIE' kina
df.loc[df['Prix'] == 'PRIX NON SPÉCIFIÉ', 'Prix'] = np.nan

# supprimer les str DH Est '/Nuit' dans la colonne de "Pix"
df.loc[:, 'Prix'] = df['Prix'].replace(r'\D', '', regex=True)
# convertir la colonne en type numerique 
df['Prix'] = pd.to_numeric(df['Prix'], errors='coerce')

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\789055699.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Prix'] = pd.to_numeric(df['Prix'], errors='coerce')

In [574]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 525 entries, 0 to 649
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Titre              525 non-null    object
 1   Localisation       525 non-null    object
 2   Prix               442 non-null    float64
 3   Nombre_chambre     523 non-null    object
 4   Nombre_douches     517 non-null    float64
 5   Surface_habitable  507 non-null    float64
 6   Type               525 non-null    object
 7   Secteur            525 non-null    object
 8   Salons             455 non-null    float64
 9   Étage              512 non-null    object
 10  Âge_du_bien        395 non-null    object
 11  link               525 non-null    object
dtypes: float64(4), object(8)
memory usage: 53.3+ KB

## 4- nettoyer la colonne

In [575]:
# supprimer '+' dans la colonne 'Nombre_chambre'

df.loc[:, 'Nombre_chambre'] = df['Nombre_chambre'].replace(r'\+', '', regex=True)

In [576]:
# Convertir les valeurs de la colonne en numérique, en remplaçant les erreurs par NaN
df['Nombre_chambre'] = pd.to_numeric(df['Nombre_chambre'], errors='coerce')



# Remplacer les valeurs NaN par 0, puis convertir la colonne en type int
df['Nombre_chambre'] = df['Nombre_chambre'].fillna(0).astype(int)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\1279112918.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nombre_chambre'] = pd.to_numeric(df['Nombre_chambre'], errors='coerce')
C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\1279112918.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nombre_chambre'] = df['Nombre_chambre'].fillna(0).astype(int)

## 5 - nettoyer la colonne de 'Nombre_douches '

In [577]:
# convertir le type de colonne 'Nombre_douches' en numerique
df['Nombre_douches'] = df['Nombre_douches'].fillna(0).astype(int)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\3255416301.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nombre_douches'] = df['Nombre_douches'].fillna(0).astype(int)

In [578]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 525 entries, 0 to 649
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Titre              525 non-null    object
 1   Localisation       525 non-null    object
 2   Prix               442 non-null    float64
 3   Nombre_chambre     525 non-null    int64
 4   Nombre_douches     525 non-null    int64
 5   Surface_habitable  507 non-null    float64
 6   Type               525 non-null    object
 7   Secteur            525 non-null    object
 8   Salons             455 non-null    float64
 9   Étage              512 non-null    object
 10  Âge_du_bien        395 non-null    object
 11  link               525 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 53.3+ KB

In [561]:
df.head(10)

,Titre,Localisation,Prix,Nombre_chambre,Nombre_douches,Surface_habitable,Type,Secteur,Salons,Étage,Âge_du_bien,link
0,APPARTEMENT À LOUER SUR CASABLANCA FINANCE CITY,Casablanca,7600.0,2,1,90.000000,NaN,Casablanca Finance City,1,1,NaN,https://www.avito.ma/fr/casablanca_finance_cit...
1,Appartement à louer neuf,Temara,5500.0,2,2,94.000000,NaN,Wifak,2,2,NaN,https://www.avito.ma/fr/wifak/appartements/App...
2,très belle appartement à louer,Agadir,300.0,3,1,96.335306,NaN,Hay Mohammadi,0,NaN,NaN,https://www.avito.ma/fr/hay_mohammadi/location...
3,appart meublé familiale sans intermédiaire Wi-Fi,Tanger,200.0,5,3,96.335306,NaN,Marjane,0,NaN,NaN,https://www.avito.ma/fr/marjane/locations_de_v...
4,Appartement à vendre 121 m² à Casablanca,Casablanca,2250000.0,3,3,121.000000,NaN,Maârif Extension,1,3,-1 ans,https://www.avito.ma/fr/ma%C3%A2rif_extension/...
5,Appartement à louer à Casablanca NearShore,Casablanca,3400.0,2,2,50.000000,NaN,Al Mostakbal,1,3,NaN,https://www.avito.ma/fr/al_mostakbal/apparteme...
6,Superbe appartement neuf a les perles a Agdal,Rabat,8000.0,1,2,60.000000,NaN,Agdal,1,7,NaN,https://www.avito.ma/fr/agdal/appartements/Sup...
7,Appart 160m Meublé Luxe A Maarif Ex,Casablanca,2250000.0,3,2,160.000000,NaN,Maarif,1,3,1-5 ans,https://www.avito.ma/fr/maarif/appartements/Ap...
8,Appartement Vente Fourate,Casablanca,1550000.0,2,2,100.000000,NaN,Maarif,2,0,NaN,https://www.avito.ma/fr/maarif/appartements/Ap...
9,Appartement à louer 80 m² à Temara,Temara,3800.0,2,1,80.000000,NaN,Riad Oulad Mtaa,1,2,NaN,https://www.avito.ma/fr/riad_oulad_mtaa/appart...

# 6- nettoyer la colonne 'Surface_habitable'

In [525]:
# la surface est nettoyer est convarti dans le type numerique

## 7- la colonne 'Type'

In [589]:
df['Type']

0       Louer
1       Louer
2       Louer
3       Louer
4      Vendre
        ...
644    Vendre
645    Vendre
647    Vendre
648    Vendre
649    Vendre
Name: Type, Length: 525, dtype: object

In [588]:
categories ={'Appartements, à vendre' : 'Vendre' ,  
             'Appartements, demande de location' : 'Location',
             'Locations de vacances, à louer':'Louer',
             'Engins agricoles, à vendre':'Avendre',
             'Porte et Fenêtre, à vendre':'Avendre',
             'Appartements, à louer':'Louer'
             
             }
df['Type']=df['Type'].map(categories)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\3143324824.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Type']=df['Type'].map(categories)

In [590]:
df.tail(10)

,Titre,Localisation,Prix,Nombre_chambre,Nombre_douches,Surface_habitable,Type,Secteur,Salons,Étage,Âge_du_bien,link
638,Appartement à vendre 96 m² à Casablanca,Casablanca,990000.0,3,2,96.0,Vendre,Ain Sebaa,2.0,1,-1 ans,https://www.avito.ma/fr/ain_sebaa/appartements...
639,Appartement à vendre 96 m² à Tanger,Tanger,1200000.0,3,2,96.0,Vendre,Marjane,1.0,3,6-10 ans,https://www.avito.ma/fr/marjane/appartements/A...
640,Marina Casablanca Appartement à vendre 115 m² à,Casablanca,3000000.0,2,3,115.0,Vendre,Sidi Belyout,1.0,2,-1 ans,https://www.avito.ma/fr/sidi_belyout/apparteme...
642,Appartement à vendre 116 m² à Casablanca,Casablanca,830000.0,3,2,116.0,Vendre,Bourgogne,1.0,2,1-5 ans,https://www.avito.ma/fr/bourgogne/appartements...
643,Bel Appartement à vendre 105 m² 2ème ètage,Agadir,930000.0,2,2,105.0,Vendre,El Houda,1.0,2,1-5 ans,https://www.avito.ma/fr/el_houda/appartements/...
644,Appartement à vendre 66 m² à Dar Bouazza,Dar Bouazza,595000.0,2,2,66.0,Vendre,Toute la ville,1.0,2,-1 ans,https://www.avito.ma/fr/dar_bouazza/appartemen...
645,Superbe appartement meublé pour vente,Tanger,1400000.0,2,1,78.0,Vendre,Branes Kdima,1.0,5,-1 ans,https://www.avito.ma/fr/branes_kdima/apparteme...
647,Appartement,Taza,370000.0,2,1,88.0,Vendre,Toute la ville,2.0,4,6-10 ans,https://www.avito.ma/fr/taza/appartements/Appa...
648,Studio-Appartement-Haut-Standing-Gueliz,Marrakech,19000.0,2,2,51.0,Vendre,Guéliz,1.0,5,-1 ans,https://www.avito.ma/fr/gu%C3%A9liz/appartemen...
649,Appartement à vendre 60 m² prés de Acima Meknès,Meknès,249999.0,2,1,60.0,Vendre,Autre secteur,1.0,1,-1 ans,https://www.avito.ma/fr/autre_secteur/appartem...

## 8 - salons

In [605]:
# convertir le type de colonne 'Nombre_douches' en numerique
df['Salons'] = df['Salons'].fillna(0).astype(int)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\655648580.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salons'] = df['Salons'].fillna(0).astype(int)

## 9 - Étage

In [579]:
df['Étage'].sort_values().unique()

array(['1', '2', '3', '4', '5', '6', '7+', '8', 'Rez de chaussée', nan],
      dtype=object)

In [580]:
df['Étage']=df['Étage'].replace('Rez de chaussée', '0')

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\4214521405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Étage']=df['Étage'].replace('Rez de chaussée', '0')

In [581]:
df.loc[:, 'Étage'] = df['Étage'].replace(r'\D', '', regex=True)

## 10 -Âge_du_bien

In [582]:
df['Âge_du_bien'].sort_values().unique()

array(['1-5 ans', '11-20 ans', '21+ ans', '6-10 ans', 'Neuf', nan],
      dtype=object)

In [583]:
df['Âge_du_bien']=df['Âge_du_bien'].replace('Neuf' , '-1 ans')

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\1200084898.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Âge_du_bien']=df['Âge_du_bien'].replace('Neuf' , '-1 ans')

## etape 2 :Gestion des Valeurs Manquantes

## salons :

In [606]:
# Display unique values in the 'Salons' column
unique_values = df['Salons'].unique()

# Display the result
print(unique_values)

[1 2 0 3]

## prix

In [607]:
# Convertir la colonne 'Prix' en numérique
df['Prix'] = pd.to_numeric(df['Prix'], errors='coerce')

# Calcul des statistiques descriptives
moyenne = df['Prix'].mean()
mediane = df['Prix'].median()

# Vérification de la distribution
if abs(moyenne - mediane) > 0.1 * moyenne:
    print("Distribution asymétrique")
else:
    print("Distribution symétrique")

Distribution asymétrique

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\343615871.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Prix'] = pd.to_numeric(df['Prix'], errors='coerce')

In [608]:
# Imputer les valeurs manquantes avec la médiane
df['Prix'] = df['Prix'].fillna(df['Prix'].median())

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\969445567.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Prix'] = df['Prix'].fillna(df['Prix'].median())

In [609]:
df.head(10)

,Titre,Localisation,Prix,Nombre_chambre,Nombre_douches,Surface_habitable,Type,Secteur,Salons,Étage,Âge_du_bien,link
0,APPARTEMENT À LOUER SUR CASABLANCA FINANCE CITY,Casablanca,7600.0,2,1,90.000000,Louer,Casablanca Finance City,1,1,NaN,https://www.avito.ma/fr/casablanca_finance_cit...
1,Appartement à louer neuf,Temara,5500.0,2,2,94.000000,Louer,Wifak,2,2,NaN,https://www.avito.ma/fr/wifak/appartements/App...
2,très belle appartement à louer,Agadir,300.0,3,1,96.335306,Louer,Hay Mohammadi,0,NaN,NaN,https://www.avito.ma/fr/hay_mohammadi/location...
3,appart meublé familiale sans intermédiaire Wi-Fi,Tanger,200.0,5,3,96.335306,Louer,Marjane,0,NaN,NaN,https://www.avito.ma/fr/marjane/locations_de_v...
4,Appartement à vendre 121 m² à Casablanca,Casablanca,2250000.0,3,3,121.000000,Vendre,Maârif Extension,1,3,6-10 ans,https://www.avito.ma/fr/ma%C3%A2rif_extension/...
5,Appartement à louer à Casablanca NearShore,Casablanca,3400.0,2,2,50.000000,Louer,Al Mostakbal,1,3,NaN,https://www.avito.ma/fr/al_mostakbal/apparteme...
6,Superbe appartement neuf a les perles a Agdal,Rabat,8000.0,1,2,60.000000,Louer,Agdal,1,7,NaN,https://www.avito.ma/fr/agdal/appartements/Sup...
7,Appart 160m Meublé Luxe A Maarif Ex,Casablanca,2250000.0,3,2,160.000000,Vendre,Maarif,1,3,1-5 ans,https://www.avito.ma/fr/maarif/appartements/Ap...
8,Appartement Vente Fourate,Casablanca,1550000.0,2,2,100.000000,Vendre,Maarif,2,0,NaN,https://www.avito.ma/fr/maarif/appartements/Ap...
9,Appartement à louer 80 m² à Temara,Temara,3800.0,2,1,80.000000,Louer,Riad Oulad Mtaa,1,2,NaN,https://www.avito.ma/fr/riad_oulad_mtaa/appart...

In [610]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 525 entries, 0 to 649
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Titre              525 non-null    object
 1   Localisation       525 non-null    object
 2   Prix               525 non-null    float64
 3   Nombre_chambre     525 non-null    int64
 4   Nombre_douches     525 non-null    int64
 5   Surface_habitable  525 non-null    float64
 6   Type               525 non-null    object
 7   Secteur            525 non-null    object
 8   Salons             525 non-null    int64
 9   Étage              512 non-null    object
 10  Âge_du_bien        395 non-null    object
 11  link               525 non-null    object
dtypes: float64(2), int64(3), object(7)
memory usage: 53.3+ KB

## surface :

In [611]:
# mean est median de colonne Surfece_habitable .
mean_surface = df['Surface_habitable'].mean()
median_surface = df['Surface_habitable'].median()

print(f"Mean of Surface_habitable: {mean_surface}")
print(f"Median of Surface_habitable: {median_surface}")

Mean of Surface_habitable: 96.3353057199211
Median of Surface_habitable: 90.0

In [612]:
# charger les valeur nan en mean ,
df['Surface_habitable'] = df['Surface_habitable'].fillna(mean_surface)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\2814968101.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Surface_habitable'] = df['Surface_habitable'].fillna(mean_surface)

In [613]:
# nest pas une valeur null
print(df['Surface_habitable'].isnull().sum())

0

## etage :

In [634]:
# Trouver la valeur la plus fréquente dans la colonne 'Étage'
mode_etage = df['Étage'].mode()[0]

# Remplir les valeurs nulles dans la colonne 'Étage' avec la valeur la plus fréquente
df['Étage'] = df['Étage'].fillna(mode_etage)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\3226799042.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Étage'] = df['Étage'].fillna(mode_etage)

## Âge_du_bien

In [636]:
# Trouver la valeur la plus fréquente dans la colonne 'Âge_du_bien'
mode_age = df['Âge_du_bien'].mode()[0]

# Remplir les valeurs nulles dans la colonne 'Âge_du_bien' avec la valeur la plus fréquente
df['Âge_du_bien'] = df['Âge_du_bien'].fillna(mode_age)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_26452\1121236240.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Âge_du_bien'] = df['Âge_du_bien'].fillna(mode_age)

In [637]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 525 entries, 0 to 649
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Titre              525 non-null    object
 1   Localisation       525 non-null    object
 2   Prix               525 non-null    float64
 3   Nombre_chambre     525 non-null    int64
 4   Nombre_douches     525 non-null    int64
 5   Surface_habitable  525 non-null    float64
 6   Type               525 non-null    object
 7   Secteur            525 non-null    object
 8   Salons             525 non-null    int64
 9   Étage              525 non-null    object
 10  Âge_du_bien        525 non-null    object
 11  link               525 non-null    object
dtypes: float64(2), int64(3), object(7)
memory usage: 53.3+ KB

In [638]:
# Sauvegarder dans un fichier CSV
df.to_csv('fichier_final_departe1ET2.csv', index=False)